.TH "COLORMYDAY" 1

.SH "NAME"
colormyday \- terminal-based visual journal

.SH "SYNOPSIS"
.sp
\fBcolormyday
.sp
\fBcolormyday begin \fIevent-name \fR[\fB--late \fItimestamp\fR]
.sp
\fBcolormyday end \fR[\fB--late \fItimestamp\fR]
.sp
\fBcolormyday show \fR[\fIshow-count\fR]

.SH "DESCRIPTION"
todo

.SH "OPTIONS"
todo

.SH "AUTHORS"

Contact at github.com/jcfk/colormyday

